version: "2.4"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ../internal/schema:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "13306:3306"